#!/bin/env bash


export _user=$(whoami)
export __dir=/home/$(whoami)/Documents/src/repos

echo $_user
echo $__dir


# pm2 start /Users/allspark/Documents/src/auth-api/server.js --name auth
# pm2 start /Users/allspark/Documents/src/data-api/server.js --name data

# cd /Users/allspark/Documents/src/test-bench

# example: pm2 start --name dashboard npm -- start

# pm2 start --name client npm -- start
